# Generated by Django 4.1.7 on 2023-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='SubCategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
