# Generated by Django 4.1.7 on 2023-05-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_alter_categorydb_categoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, max_length=100000, null=True)),
                ('Sub_Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='ProductImg')),
            ],
        ),
    ]
