# Generated by Django 4.1.7 on 2023-05-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uNAME', models.CharField(blank=True, max_length=10, null=True)),
                ('uPASS', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
