# Generated by Django 4.1.7 on 2023-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
