# Generated by Django 4.1.7 on 2023-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_checkoutdb_address_checkoutdb_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdb',
            name='Phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdb',
            name='Pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
